#################################
#         DAY 1                 #
#################################


### Good coding practice ####

# Put hard-coded objects/values at the beginning of the script.
#   e.g.: required packages, working directory, reading data

# There is no such thing as too many comments!

# Use line breaks to avoid too many words per line

# Use indentation to structure commands

# Use spaces before and after operators (assign arrows, logical operators, etc.)

# Use chapters in scripts and/or modularize your workflow (e.g. using functions)

#####


### R data and object types ####
# also have a look at: http://www.statmethods.net/input/datatypes.html

# we will make up some data to look at common data and object types in R


### vectors
x <- c(1:5, 16:20)
str(x)
class(x)
# integer

# What are the data types of the following vectors?
y <- round(jitter(x), 2)
a <- rep(c("A", "B"), 5)
b <- as.factor(a)
levels(b)
c <- a == "A"

# As part of the last 4 lines of code, we already used several new commands
# as well as nested commands
?round
?jitter
?rep
?as.factor
?levels

# What is the difference between '=' and '=='?
# Which other logical operators do you know?
# What is the operator for 'not equal'?
a != "A"
"A" %in% a
c("A", "B", "C") %in% a
# and: &
# or: |
# less than: <
# less than or equal <=
y >= 5 | a == "A"

# data type conversions
# Which data types are generated by the next 4 lines of code?
n <- as.numeric(b)
as.numeric(a)
as.numeric(as.factor(a))
d <- rep(c("1", "B"), 5)
as.numeric(d)

# numeric to factor
m <- as.factor(x)

# factor with numeric levels to numeric
as.numeric(m)
m1 <- as.numeric(as.character(m))
# Why does 'as.numeric(m)' not reproduce the original numeric vector?


### matrices: "vectors with line breaks"
# same data type
X <- matrix(
  data = 1:50, # vector is input for matrix command
  nrow = 10, # how many rows
  ncol = 5, # how many column
  byrow = F # fill by column
)
X
# What happens if 'byrow' is set to TRUE?
# What happens if the input data does not match the dimensions of the matrix?
# Hint: modify either data or nrow
# Which error messages are reported

# character matrix
A <- matrix(
  rep(c("A","B"), 25), 
  nrow = 10,
  ncol = 5, 
  byrow = F
)

# convert to vector
c(X)


### data frames: concatenated (list of) vectors
# therefore they can consist of different data types (as columns)
DF <- data.frame(x, y, a, b, c)
DF
# Which data type do the different columns in this data.frame have?
str(DF)
# What happens if you use the function argument stringsAsFactors = T?
DF2 <- data.frame(x, y, a, b, c, stringsAsFactors = T)

# What happens when we transpose a data.frame consisting of different data types and why?
tDF <- t(DF)


### lists: vectors consisting of R objects, including other lists
L <- list(x, y, a, b, c, X, A, DF)

#####


### R object attributes ####
# names, column names, row names
# need to be unique identifiers

# vectors and lists
names(x) <- c("S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10")
str(x)
# remove names
names(x) <- NULL

# name elements of a list
names(L) <- c("int", "num", "chr", "fac", "log", "mat.int", "mat.chr", "df")

# matrices and data frames
rownames(X) <- c("S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10")
colnames(X) <- c("V1", "V2", "V3", "V4", "V5")

rownames(DF) <- c("S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S11")
colnames(DF) # already exist, based on names of input vectors

# avoid starting row and column names with numbers!
# avoid special characters as part of row and column names (replaced by '.')

#####


#### navigating R objects ####
# square brackets: [rows, columns] or if only one dimension [position]

### vectors
x
# select 3rd element in vector
x[3]

# select 3rd to 5th elements in vector
x[3:5]

# select 2st, 3rd, 7th element in vector
x[c(2, 3, 7)]

# select everything except 3rd element
x[-3]
x[-c(2, 3, 7)]

# selection based on attributes: elements "S3" and "S5"
x["S3"]


### matrices and data frames
X
DF
# select first 3 rows
X[1:3, ]

# select first 3 column
X[, 1:3]

# select second element in 3rd row
X[3, 2]

# selection based on attributes: row "S1" and columns "V3" and "V5"
X["S1", c("V3", "V5")]

# select columns "c", "a", and "x" from DF ...
# ... with changing original order
DF[, c("c", "a", "x")]

# ... without changing original order
DF[, colnames(DF) %in% c("c", "a", "x")]

# extract column "y" from DF

# subset DF to all rows where the values of column "y" are larger than 3
DF[DF$y > 3, ]

# in DF, select values of column "x" where column "y" is larger than 3
DF[DF$y > 3, "x", drop = F]

# using logical operators, subset DF to all rows where column "y" is larger than 3 and/or column "a" is "A"


# use dollar '$' to extract columns in data frame by column name
DF$x

# What happens when you try to select columns in a matrix with '$' and why?
X
DF
  
# How does subsetting the matrix/data.frame change the object type?


### navigating lists
# return a subset of the list: single square brackets
# the output will still be a list
L.sub <- L[1]
class(L[1])

# return an element of a list: '$' or double square brackets
# the output will have the object and data type of the element of the list
L.int <- L$int
str(L$df)
str(L[8])
str(x)


### all R objects are saved in a workspace
# to use these objects on the next R session, save the workspace
# default location of your workspace is your home directory
# to work in a different directory
setwd("your/working/directory")

# save workspace
# CAUTION: don't overwrite an existing workspace with an empty one
save.image("R_objects.Rdata")

# load workspace
load("R_objects.Rdata")

# clear workspace
rm(list = ls())

#####


### Reading data into R ####

# set your working directory to where you saved the course material

# clear workspace if required
rm(list = ls())

# we have tab-separated data
# R also reads csv and space-separated
# since commas and spaces may also occur in the data, I prefer tabstops
# decimal separator is '.' by default, but can also be changed
# there are many more file types that can be read by R, mostly using package-specific functions

# bacterial community data
OTU <- read.table(
  "OTU_table.txt", # file name
  h = T, # first line contains column names
  sep = "\t", # values separated by tabstops
  row.names = 1 # first row contains row names, i.e. OTU names
)
head(OTU)

# bottom water data (carbonate chemistry, nutrients)
ENV <- read.table(
  "ENV_table.txt",
  h = T, 
  sep = "\t"
)
head(ENV)

# taxonomy of microbial community
TAX <- read.table(
  "TAX_table.txt",
  h = T, 
  sep = "\t", 
  row.names = 1, # first row contains row names, i.e. OTU names
  stringsAsFactors = F, # to prevent character strings to be interpreted as factors, for taxonomy files factors sometimes also useful
  comment.char = "", # to account for weird symbols (#) in taxon names
  quote = "" # to account for weird symbols (", ') in taxon names
)
head(TAX)

# for more info, use help option
?read.table

# inspect data frames
dim(ENV)
dim(OTU)
dim(TAX)

# more information on content of data frames
str(OTU)
str(ENV)
str(TAX)

# Are the data and object types correct? If not, modify the object and data types as required

# How does data type affect plotting behavior? 
plot(ENV$pH ~ ENV$seep.code)
plot(ENV$pH ~ ENV$seep.category) # returns an error
plot(ENV$pH ~ as.factor(ENV$seep.category))

# change site and reef and seep.category to factors
# change seep.code to factor
ENV$reef <- as.factor(ENV$reef)
ENV$seep.category <- factor(ENV$seep.category, levels = c("reference", "medium", "high"))
ENV <- ENV[order(ENV$seep.category), ]
ENV$site <- factor(ENV$site, levels = unique(ENV$site))
levels(ENV$site)

# show plots again
plot(ENV$pH ~ ENV$seep.category)
plot(ENV$pH ~ ENV$site)

# Why can't we store all data in one R object?
# How do can we make sure that data in different objects stays comparable?
colnames(OTU)
OTU <- OTU[, levels(ENV$site)]
colnames(OTU)
all.equal(
  colnames(OTU), 
  levels(ENV$site)
)

# compare the order of OTUs in OTU and TAX tables
# row names are OTU names
all.equal(
  rownames(OTU), 
  rownames(TAX)
)

# Prepare plotting parameters
# Add an additional column to ENV encoding the color scheme for seep category
ENV$color <- ENV$seep.category
levels(ENV$color) <- c("blue", "orange", "red")
plot(ENV$SiO4 ~ ENV$pH, col = as.character(ENV$color), pch = 16)
# plot(ENV$SiO4 ~ ENV$pH, col = ENV$color, pch = 16)
legend("topright", legend = levels(ENV$seep.category), col = levels(ENV$color), pch = 16)

#####